name: 'portfolio_analytics'
version: '1.0.0'
config-version: 2

profile: 'portfolio'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  portfolio_analytics:
    staging:
      +materialized: view
      +schema: staging
    
    intermediate:
      +materialized: view
      +schema: intermediate
    
    marts:
      +materialized: table
      +schema: marts

seeds:
  portfolio_analytics:
    +schema: seeds
