portfolio:
  target: dev
  outputs:
    # All environments use S3 - switching is done via env vars
    # Local: S3_ENDPOINT_HOST=localhost:4567 (LocalStack)
    # Prod:  S3_ENDPOINT_HOST= (empty for AWS default)
    dev:
      type: duckdb
      path: ':memory:'
      threads: 4
      extensions:
        - httpfs
      settings:
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID', '') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY', '') }}"
        s3_endpoint: "{{ env_var('S3_ENDPOINT_HOST', '') }}"
        s3_region: "{{ env_var('S3_REGION', 'us-east-1') }}"
        s3_url_style: "path"
        s3_use_ssl: "{{ env_var('S3_USE_SSL', 'false') }}"
