portfolio:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/portfolio.duckdb'
      threads: 4
      
    prod:
      type: duckdb
      path: '../data/portfolio.duckdb'
      threads: 4
