version: 2

# =============================================================================
# S3 EXTERNAL SOURCES
# =============================================================================
# All data is stored as Parquet files on S3-compatible storage.
# Environment switching is done via S3 configuration (endpoint, bucket).
#
# Local dev:  S3_ENDPOINT_HOST=localhost:4567  (LocalStack)
# Production: S3_ENDPOINT_HOST=s3.amazonaws.com (or empty for AWS default)
#
# Prerequisites:
#   - S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY environment variables
#   - S3_BUCKET, S3_PREFIX environment variables
#   - Data loaded via ingestion scripts
# =============================================================================

sources:
  # =============================================================================
  # RAW MARKET DATA
  # =============================================================================
  - name: raw
    description: Raw market data stored as Parquet files on S3
    meta:
      external_location: "read_parquet('s3://{{ env_var('S3_BUCKET', 'portfolio-analytics') }}/{{ env_var('S3_PREFIX', 'data') }}/raw/{name}.parquet')"
    tables:
      - name: raw_prices
        description: Historical price data for equities/ETFs

      - name: raw_benchmark_prices
        description: Benchmark (S&P 500) price data

      - name: raw_treasury_yields
        description: Treasury yield curve data from FRED

      - name: raw_fund_metadata
        description: Fund metadata from Yahoo Finance API

      - name: raw_analyst_targets
        description: Analyst price targets from Yahoo Finance API

  # =============================================================================
  # POSTGRES REPLICATED DATA
  # =============================================================================
  - name: postgres
    description: Replicated tables from Postgres stored as Parquet on S3
    meta:
      external_location: "read_parquet('s3://{{ env_var('S3_BUCKET', 'portfolio-analytics') }}/{{ env_var('S3_PREFIX', 'data') }}/raw/{name}.parquet')"
    tables:
      - name: pg_portfolio
        description: Portfolio/account ownership

      - name: pg_security_registry
        description: Canonical security identity

      - name: pg_security_identifier
        description: Multiple identifiers per security

      - name: pg_equity_details
        description: Equity/ETF subtype details

      - name: pg_bond_details
        description: Bond subtype details

      - name: pg_transaction_ledger
        description: Append-only transaction ledger

      - name: pg_position_current
        description: Current positions

      - name: pg_cash_balance
        description: Cash balances per portfolio per currency

  # =============================================================================
  # SEED DATA (uploaded to S3)
  # =============================================================================
  - name: seeds
    description: Seed data uploaded to S3
    meta:
      external_location: "read_parquet('s3://{{ env_var('S3_BUCKET', 'portfolio-analytics') }}/{{ env_var('S3_PREFIX', 'data') }}/seeds/{name}.parquet')"
    tables:
      - name: holdings
        description: Reference holdings data
